# Generated by Django 5.0.11 on 2025-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0003_invoice_invoiceline_invoice_idx_inv_tb_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('tenant', 'product', 'content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='inventory',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supply_chain',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
    ]
