# Generated by Django 5.0.11 on 2025-08-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_inventory_unique_together_inventory_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
