# Generated by Django 5.0.11 on 2025-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supply_chain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
