# Generated by Django 5.0.11 on 2025-08-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_inventory_unique_together_inventory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
