# Generated by Django 5.0.11 on 2025-09-02 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0007_alter_inventory_name_alter_inventory_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('INBOUND_RECEIPT', 'Inbound Receipt'), ('DISPATCH_TO_BRANCH', 'Dispatch to Branch'), ('RECEIVE_FROM_WAREHOUSE', 'Receive from Warehouse'), ('RESERVE', 'Reserve'), ('UNRESERVE', 'Unreserve'), ('CONSUME_RESERVATION', 'Consume Reservation'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RETURN_TO_WAREHOUSE', 'Return to Warehouse'), ('RETURN_TO_SUPPLIER', 'Return to Supplier')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16)),
                ('from_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('to_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('ref_type', models.CharField(blank=True, max_length=32, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=64, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.BigIntegerField(editable=False)),
                ('last_modified', models.BigIntegerField(editable=False)),
            ],
            options={
                'db_table': 'stock_movement',
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['tenant', 'product', 'content_type', 'object_id'], name='idx_inv_tpc_loc'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'content_type', 'object_id'), name='uq_inv_tenant_product_location'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('qty__gte', 0)), name='ck_inv_qty_nonnegative'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='stockmovement_created_by', to='products.agent'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sm_from_ct', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockmovement_modified_by', to='products.agent'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(db_column='tenant', on_delete=django.db.models.deletion.CASCADE, to='products.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sm_to_ct', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'product', 'date_created'], name='idx_sm_tpp_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'status'], name='idx_sm_type_status'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['from_content_type', 'from_object_id'], name='idx_sm_from'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['to_content_type', 'to_object_id'], name='idx_sm_to'),
        ),
    ]
