# Generated by Django 5.0.11 on 2025-09-02 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockmovement_inventory_idx_inv_tpc_loc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('transfer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('POSTED', 'Posted')], default='POSTED', max_length=16)),
                ('dispatch_movement_id', models.IntegerField(blank=True, null=True)),
                ('receive_movement_id', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.agent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.warehouse')),
            ],
            options={
                'db_table': 'stock_transfer',
                'indexes': [models.Index(fields=['tenant', 'date_created'], name='stock_trans_tenant__513c1c_idx'), models.Index(fields=['product', 'branch'], name='stock_trans_product_e51bc3_idx')],
            },
        ),
    ]
